Try to fix the GitHub Action Error Below:
Build/Setup Ruby

3s
Run ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
Modifying PATH
Downloading Ruby
Extracting  Ruby
Print Ruby version
Installing Bundler
> bundle install
/opt/hostedtoolcache/Ruby/3.4.1/x64/bin/bundle config --local path /home/runner/work/awesome-music/awesome-music/vendor/bundle
[DEPRECATED] Using the `config` command without a subcommand [list, get, set, unset] is deprecated and will be removed in the future. Use `bundle config set --local path /home/runner/work/awesome-music/awesome-music/vendor/bundle` instead.
/opt/hostedtoolcache/Ruby/3.4.1/x64/bin/bundle config --local deployment true
[DEPRECATED] Using the `config` command without a subcommand [list, get, set, unset] is deprecated and will be removed in the future. Use `bundle config set --local deployment true` instead.
Cache key: setup-ruby-bundler-cache-v6-ubuntu-24.04-x64-ruby-3.4.1-wd-/home/runner/work/awesome-music/awesome-music-with--without--only--Gemfile.lock-8475a5a2a02ad1dad1f5aeeea5aa1b9c24e325b4026e2a494e36c2861a758865
Warning: Failed to restore: Cache service responded with 400
/opt/hostedtoolcache/Ruby/3.4.1/x64/bin/bundle install --jobs 4
[DEPRECATED] Platform :mingw, :x64_mingw, :mswin will be removed in the future. Please use platform :windows instead.
Your bundle only supports platforms ["x64-mingw-ucrt"] but your local platform
is x86_64-linux. Add the current platform to the lockfile with
`bundle lock --add-platform x86_64-linux` and try again.
Error: The process '/opt/hostedtoolcache/Ruby/3.4.1/x64/bin/bundle' failed with exit code 16